# 프로그램의 입력과 출력

## 사용자 입력과 출력

In [ ]:
a = input()

안녕하세요? Hello!

In [ ]:
a

'안녕하세요? Hello!'

In [ ]:
number = input("숫자를 입력하세요: ")

숫자를 입력하세요: 5

In [ ]:
print(number)

5

print 사용예

In [ ]:
a = 123
print(a)
b = "Python"
print(b)
c = [1, 2, 3]
print(c)

123
Python
[1, 2, 3]

In [ ]:
print("life" "is" "too short") # ①
print("life"+"is"+"too short") # ②

lifeistoo short
lifeistoo short

In [ ]:
print("life", "is", "too short")

life is too short

In [ ]:
for i in range(10):
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9

## 파일 읽기 쓰기

In [ ]:
f = open("새파일.txt", 'w')
f.close()

In [ ]:
f = open("새파일.txt", 'w')
for i in range(1, 11):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

In [ ]:
f = open("새파일.txt", 'r')
line = f.readline()
print(line)
f.close()

1번째 줄입니다.

In [ ]:
f = open("새파일.txt", 'r')
while True:
    line = f.readline()
    if not line: break
    print(line)
f.close()

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

In [ ]:
f = open("새파일.txt", 'r')
lines = f.readlines()
for line in lines:
    print(line)
f.close()

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

In [ ]:
f = open("새파일.txt", 'r')
data = f.read()
print(data)
f.close()

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.

In [ ]:
f = open("새파일.txt",'a')
for i in range(11, 20):
    data = "%d번째 줄입니다.\n" % i
    f.write(data)
f.close()

In [ ]:
f = open("새파일.txt", 'r')
data = f.read()
print(data)
f.close()

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.
11번째 줄입니다.
12번째 줄입니다.
13번째 줄입니다.
14번째 줄입니다.
15번째 줄입니다.
16번째 줄입니다.
17번째 줄입니다.
18번째 줄입니다.
19번째 줄입니다.

In [ ]:
f = open("NOwith.txt", 'w')
f.write("Life is too short, you need python")
f.close()

In [ ]:
with open("with.txt", "w") as f:
    f.write("Life is too short, you need python")

Quiz

In [ ]:
input1 = int(input("첫번째 숫자를 입력하세요:"))
input2 = int(input("두번째 숫자를 입력하세요:"))

total = input1 + input2
print("두 수의 합은 %s 입니다" % total)

첫번째 숫자를 입력하세요:5
두번째 숫자를 입력하세요:15
두 수의 합은 20 입니다

# 데이터 적재

## 라이브러리 데이터 셋 로드

In [ ]:
# 보스턴 데이터 셋 로드
from sklearn.datasets import load_boston

boston=load_boston()

boston.data.shape

(506, 13)

In [ ]:
boston_features=boston.data

boston_features[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [ ]:
boston_features[0:4]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00]])

In [ ]:
# head() 함수 이용해 행 조회
import pandas as pd
boston_df=pd.DataFrame(boston_features)

boston_df.head()

        0     1     2    3      4   ...   8      9     10      11    12
0  0.00632  18.0  2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90  4.98
1  0.02731   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90  9.14
2  0.02729   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83  4.03
3  0.03237   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  394.63  2.94
4  0.06905   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  396.90  5.33

[5 rows x 13 columns]

In [ ]:
boston_df.head(7)

        0     1     2    3      4   ...   8      9     10      11     12
0  0.00632  18.0  2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90   4.98
1  0.02731   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90   9.14
2  0.02729   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83   4.03
3  0.03237   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  394.63   2.94
4  0.06905   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  396.90   5.33
5  0.02985   0.0  2.18  0.0  0.458  ...  3.0  222.0  18.7  394.12   5.21
6  0.08829  12.5  7.87  0.0  0.524  ...  5.0  311.0  15.2  395.60  12.43

[7 rows x 13 columns]

In [ ]:
boston_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       506 non-null    float64
 1   1       506 non-null    float64
 2   2       506 non-null    float64
 3   3       506 non-null    float64
 4   4       506 non-null    float64
 5   5       506 non-null    float64
 6   6       506 non-null    float64
 7   7       506 non-null    float64
 8   8       506 non-null    float64
 9   9       506 non-null    float64
 10  10      506 non-null    float64
 11  11      506 non-null    float64
 12  12      506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB

In [ ]:
boston_df.columns

RangeIndex(start=0, stop=13, step=1)

## 물리적인 파일 데이터 셋 로드

In [ ]:
!git clone https://github.com/onlookertozip/bigStudy.git

Cloning into 'bigStudy'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 64 (delta 29), reused 11 (delta 5), pack-reused 0
Unpacking objects: 100% (64/64), done.

csv

In [ ]:
import pandas as pd

In [ ]:
diamonds_df=pd.read_csv("bigStudy/diamonds.csv")

In [ ]:
diamonds_df.head(5)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [ ]:
diamonds_df.tail(5)

       carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [ ]:
import pandas as pd

엑셀

In [ ]:
diamonds_xl=pd.read_excel("bigStudy/diamonds.xlsx", sheet_name=0, header=0)

In [ ]:
diamonds_xl.head(5)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

json 파일

In [ ]:
import csv
import json

In [ ]:
csvfile=open('bigStudy/diamonds.csv','r')
jsonfile=open('bigStudy/diamonds.json','w')

In [ ]:
fieldnames=("FirstName","LastName","IDNumber","Message")
reader=csv.DictReader(csvfile, fieldnames)

In [ ]:
out=json.dumps([row for row in reader])
jsonfile.write(out)

7303173

In [ ]:
import pandas as pd

url='bigStudy/diamonds.json'

diamonds_json=pd.read_json(url, orient='columns')

In [ ]:
diamonds_json.head(5)

  FirstName LastName IDNumber  Message                               null
0     carat      cut    color  clarity     [depth, table, price, x, y, z]
1      0.23    Ideal        E      SI2  [61.5, 55, 326, 3.95, 3.98, 2.43]
2      0.21  Premium        E      SI1  [59.8, 61, 326, 3.89, 3.84, 2.31]
3      0.23     Good        E      VS1  [56.9, 65, 327, 4.05, 4.07, 2.31]
4      0.29  Premium        I      VS2   [62.4, 58, 334, 4.2, 4.23, 2.63]

 SQLite

In [ ]:
import sqlite3
print(sqlite3.version)
print(sqlite3.sqlite_version)

2.6.0
3.22.0

In [ ]:
# DB 연결, 커서 획득
# DB 생성 (오토 커밋)
conn = sqlite3.connect("test.db", isolation_level=None)
# 커서 획득
c = conn.cursor()
# 테이블 생성 (데이터 타입은 TEST, NUMERIC, INTEGER, REAL, BLOB 등)
c.execute("CREATE TABLE IF NOT EXISTS table1 \
    (id integer PRIMARY KEY, name text, birthday text)")

In [ ]:
# 데이터 삽입 방법 1
c.execute("INSERT INTO table1 \
    VALUES(1, 'LEE', '1987-00-00')")

In [ ]:
# 데이터 삽입 방법 2
c.execute("INSERT INTO table1(id, name, birthday) \
    VALUES(?,?,?)", \
    (2, 'KIM', '1990-00-00'))

In [ ]:
test_tuple = (
    (3, 'PARK', '1991-00-00'),
    (4, 'CHOI', '1999-00-00'),
    (5, 'JUNG', '1989-00-00')
)
c.executemany("INSERT INTO table1(id, name, birthday) VALUES(?,?,?)", test_tuple)

In [ ]:
# 데이터 불러오기
c.execute("SELECT * FROM table1")
print(c.fetchone())
print(c.fetchone())
print(c.fetchall())

(1, 'LEE', '1987-00-00')
(2, 'KIM', '1990-00-00')
[(3, 'PARK', '1991-00-00'), (4, 'CHOI', '1999-00-00'), (5, 'JUNG', '1989-00-00')]

In [ ]:
# 전체 데이터
c.execute("SELECT * FROM table1")
print(c.fetchall())

[(1, 'LEE', '1987-00-00'), (2, 'KIM', '1990-00-00'), (3, 'PARK', '1991-00-00'), (4, 'CHOI', '1999-00-00'), (5, 'JUNG', '1989-00-00')]

In [ ]:
# 리스트 형태로 출력
# 방법 1
c.execute("SELECT * FROM table1")
for row in c.fetchall():
    print(row)
# 방법 2
for row in c.execute("SELECT * FROM table1 ORDER BY id ASC"):
    print(row)

(1, 'LEE', '1987-00-00')
(2, 'KIM', '1990-00-00')
(3, 'PARK', '1991-00-00')
(4, 'CHOI', '1999-00-00')
(5, 'JUNG', '1989-00-00')
(1, 'LEE', '1987-00-00')
(2, 'KIM', '1990-00-00')
(3, 'PARK', '1991-00-00')
(4, 'CHOI', '1999-00-00')
(5, 'JUNG', '1989-00-00')

In [ ]:
# 데이터 수정

# 방법 1
c.execute("UPDATE table1 SET name=? WHERE id=?", ('NEW1', 1))
# 방법 2
c.execute("UPDATE table1 SET name=:name WHERE id=:id", {"name": 'NEW2', 'id': 3})
# 방법 3
c.execute("UPDATE table1 SET name='%s' WHERE id='%s'" % ('NEW3', 5))
# 확인
for row in c.execute('SELECT * FROM table1'):
    print(row)

(1, 'NEW1', '1987-00-00')
(2, 'KIM', '1990-00-00')
(3, 'NEW2', '1991-00-00')
(4, 'CHOI', '1999-00-00')
(5, 'NEW3', '1989-00-00')

In [ ]:
# 데이터 삭제하기

# 방법 1
c.execute("DELETE FROM table1 WHERE id=?", (1,))
# 방법 2
c.execute("DELETE FROM table1 WHERE id=:id", {'id': 3})
# 방법 3
c.execute("DELETE FROM table1 WHERE id='%s'" % 5)
# 확인
for row in c.execute('SELECT * FROM table1'):
    print(row)

(2, 'KIM', '1990-00-00')
(4, 'CHOI', '1999-00-00')

In [ ]:
# DB 백업하기 (dump)

with conn:
    with open('dump.sql', 'w') as f:
        for line in conn.iterdump():
            f.write('%s\n' % line)
        print('Completed.')

Completed.

In [ ]:
# DB 연결 해제
conn.close()

## CSV파일 열고 내보내기

In [2]:
import pandas as pd

url = 'https://github.com/onlookertozip/bigStudy/blob/master/phone.xlsx?raw=true'

In [3]:
스마트폰=pd.read_excel(url)

In [4]:
스마트폰.head()

   Unnamed: 0 스마트폰 관련  ...           Unnamed: 8        Unnamed: 9
0         NaN    출시년도  ...  평균 컴퓨터\n사용시간\n(분/일)  데이터\n사용량\n(mb/일)
1         1.0    2015  ...                  500               100
2         2.0    2014  ...                   30                50
3         3.0    2015  ...                  300               200
4         4.0    2015  ...                   60               190

[5 rows x 10 columns]

In [5]:
# 행 개수
len(스마트폰)

25

In [6]:
# 열 개수
len(스마트폰.columns)

10

In [7]:
스마트폰.shape

(25, 10)

In [8]:
스마트폰.to_csv('스마트폰.csv')