#사이킷런(sklearn)

패키지 로드

In [ ]:
import numpy as np                                       ## 기초 수학 연산 및 행렬계산
import pandas as pd                                      ## 데이터프레임 사용
from sklearn import datasets                             ## iris와 같은 내장 데이터 사용
from sklearn.model_selection import train_test_split     ## train, test 데이터 분할

from sklearn.linear_model import LinearRegression        ## 선형 회귀분석
from sklearn.linear_model import LogisticRegression      ## 로지스틱 회귀분석
from sklearn.naive_bayes import GaussianNB               ## 나이브 베이즈
from sklearn import svm                                  ## 서포트 벡터 머신
from sklearn import tree                                 ## 의사결정나무
from sklearn.ensemble import RandomForestClassifier      ## 랜덤포레스트

import matplotlib.pyplot as plt                          ## plot 그릴때 사용

가상 데이터 생성

In [ ]:
# 분류용 가상 데이터 만들기
from sklearn.datasets import make_classification

In [ ]:
X, Y = make_classification(n_samples=1000, n_features=4,
                        n_informative=2, n_redundant=0,
                        random_state=0, shuffle=False)

데이터 불러오기

In [ ]:
raw = datasets.load_breast_cancer()         ## sklearn에 내장된 원본 데이터 불러오기
print(raw.feature_names)                    ## 열(column) 이름 확인
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

data = pd.DataFrame(raw.data)               ## 독립변수 데이터 모음  
target = pd.DataFrame(raw.target)           ## 종속변수 데이터 모음
rawData = pd.concat([data,target], axis=1)  ## 독립변수 + 종속변수 열 결합

## 열(column)이름 설정
rawData.columns=['mean radius', 'mean texture', 'mean perimeter', 'mean area',
 'mean smoothness', 'mean compactness', 'mean concavity',
 'mean concave points', 'mean symmetry', 'mean fractal dimension',
 'radius error', 'texture error', 'perimeter error', 'area error',
 'smoothness error', 'compactness error', 'concavity error',
 'concave points error', 'symmetry error', 'fractal dimension error',
 'worst radius', 'worst texture', 'worst perimeter', 'worst area',
 'worst smoothness', 'worst compactness', 'worst concavity',
 'worst concave points', 'worst symmetry', 'worst fractal dimension'
 , 'cancer']

rawData.head(10)                                ## 데이터 확인

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

   mean radius  mean texture  ...  worst fractal dimension  cancer
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0
5        12.45         15.70  ...                  0.12440       0
6        18.25         19.98  ...                  0.08368       0
7        13.71         20.83  ...                  0.11510       0
8        13.00         21.82  ...                  0.10720       0
9        12.46         24.04  ...                  0.20750       0

[10 rows x 31 columns]

In [ ]:
x = rawData[['mean radius', 'mean texture']]
y = rawData['cancer']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=0)

선형회귀분석

In [ ]:
clf = LinearRegression()
clf.fit(x_train,y_train)  # 모수 추정
clf.coef_                 # 추정 된 모수 확인(상수항 제외)
clf.intercept_            # 추정 된 상수항 확인
clf.predict(x_test)        # 예측
clf.score(x_test, y_test) # 모형 성능 평가

0.6092200214592733

로지스틱 회귀분석

In [ ]:
clf = LogisticRegression(solver='lbfgs').fit(x_train,y_train)
clf.predict(x_test)
clf.predict_proba(x_test)
clf.score(x_test,y_test)

0.9020979020979021

나이브 베이즈

In [ ]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)
gnb.predict(x_test)
gnb.score(x_test, y_test)

0.8951048951048951

의사결정 나무

In [ ]:
clf = tree.DecisionTreeClassifier()
clf.fit(x_train, y_train)
clf.predict(x_test)
clf.predict_proba(x_test)
clf.score(x_test, y_test)

0.8601398601398601

서포트벡터머신

In [ ]:
clf = svm.SVC(kernel='linear')
clf.fit(x_train, y_train)
clf.predict(x_test)
clf.score(x_test, y_test)

0.9020979020979021

랜덤포레스트

In [ ]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(x_train, y_train)
clf.feature_importances_
clf.predict(x_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0])

#1. Quiz

대화하는 프로그램 만들기

In [1]:
itemPrice = int(input("물건값을 입력하시오: "))
note = int(input("1000원 지폐개수: "))
coin500 = int(input("500원 동전개수: "))
coin100 = int(input("100원 동전개수: "))

change = note*1000 + coin500*500 + coin100*100 - itemPrice

# 거스름돈(500원 동전 개수)을 계산한다. 
nCoin500 = change//500
change = change%500

# 거스름돈(100원 동전 개수)을 계산한다. 
nCoin100 = change//100
change = change%100

# 거스름돈(10원 동전 개수)을 계산한다. 
nCoin10 = change//10
change = change%10

# 거스름돈(1원 동전 개수)을 계산한다. 
nCoin1 = change

print("500원=", nCoin500, "100원=", nCoin100, "10원=", nCoin10, "1원=", nCoin1)

물건값을 입력하시오: 10
1000원 지폐개수: 10
500원 동전개수: 50
100원 동전개수: 10
500원= 71 100원= 4 10원= 9 1원= 0

In [2]:
menu = 0
friends = []
while menu != 9:
    print("--------------------")
    print("1. 친구 리스트 출력")
    print("2. 친구추가")
    print("3. 친구삭제")
    print("4. 이름변경")
    print("9. 종료")
    menu = int(input("메뉴를 선택하시오: "))
    if menu == 1:
        print(friends)
    elif  menu== 2:
        name = input("이름을 입력하시오: ")
        friends.append(name)
menu = 0
friends = []
while menu != 9:
    print("--------------------")
    print("1. 친구 리스트 출력")
    print("2. 친구추가")
    print("3. 친구삭제")
    print("4. 이름변경")
    print("9. 종료")
    menu = int(input("메뉴를 선택하시오: "))
    if menu == 1:
        print(friends)
    elif  menu== 2:
        name = input("이름을 입력하시오: ")
        friends.append(name)

--------------------
1. 친구 리스트 출력
2. 친구추가
3. 친구삭제
4. 이름변경
9. 종료
메뉴를 선택하시오: 1
[]
--------------------
1. 친구 리스트 출력
2. 친구추가
3. 친구삭제
4. 이름변경
9. 종료
메뉴를 선택하시오: 9
--------------------
1. 친구 리스트 출력
2. 친구추가
3. 친구삭제
4. 이름변경
9. 종료
메뉴를 선택하시오: 2
이름을 입력하시오: 홍길동
--------------------
1. 친구 리스트 출력
2. 친구추가
3. 친구삭제
4. 이름변경
9. 종료
메뉴를 선택하시오: 1
['홍길동']
--------------------
1. 친구 리스트 출력
2. 친구추가
3. 친구삭제
4. 이름변경
9. 종료
메뉴를 선택하시오: 9

파일에서 중복되지 않은 단어의 개수

In [ ]:
# 단어에서 구두점을 제거하고 소문자로 만든다. 
def process(w):		
	output =""
	for ch in w:
		if( ch.isalpha() ):
			output += ch
	return output.lower()

words = set()
# 파일을 연다.
fname = input("입력 파일 이름: ")
file = open(fname, "r")
# 파일의 모든 줄에 대하여 반복한다.
for line in file:
        lineWords = line.split()
        for word in lineWords:	
            words.add(process(word))	# 단어를 세트에 추가한다.
print("사용된 단어의 개수=", len(words))
print(words)

단어 카운터

In [ ]:
fname = input("파일 이름: ")
file = open(fname, "r")

table = dict()
for line in file:
    words = line.split()
    for word in words:
        if word not in table:
            table[word] = 1
        else:
            table[word] += 1

print(table)

은행 계좌

In [3]:
class BankAccount:
    def __init__(self):
        self.__balance = 0

    def withdraw(self, amount):
        self.__balance -= amount
        print("통장에 ", amount, "가 입금되었음")
        return self.__balance

    def deposit(self, amount):
        self.__balance += amount
        print("통장에서 ", amount, "가 출금되었음")
        return self.__balance

a = BankAccount()
a.deposit(100)
a.withdraw(10)

통장에서  100 가 출금되었음
통장에  10 가 입금되었음

90

# 2. 포트폴리오

In [ ]:
import pandas as pd

In [ ]:
스마트폰=pd.read_excel("phone.xlsx")

# EDA

In [ ]:
스마트폰.head()

   Unnamed: 0 스마트폰 관련  ...           Unnamed: 8        Unnamed: 9
0         NaN    출시년도  ...  평균 컴퓨터\n사용시간\n(분/일)  데이터\n사용량\n(mb/일)
1         1.0    2015  ...                  500               100
2         2.0    2014  ...                   30                50
3         3.0    2015  ...                  300               200
4         4.0    2015  ...                   60               190

[5 rows x 10 columns]

In [ ]:
# 행 개수
len(스마트폰)

25

In [ ]:
# 열 개수
len(스마트폰.columns)

10

In [ ]:
스마트폰.shape

(25, 10)

In [ ]:
# Null 값이 아닌 행 개수
스마트폰.count()

Unnamed: 0    24
스마트폰 관련       25
Unnamed: 2    25
Unnamed: 3    25
사용자 관련        25
Unnamed: 5    25
Unnamed: 6    25
Unnamed: 7    25
Unnamed: 8    25
Unnamed: 9    25
dtype: int64

In [ ]:
스마트폰['Unnamed: 0'].count()

24

In [ ]:
# 그룹별 개수 구하기
스마트폰.groupby('Unnamed: 0').size()
스마트폰.groupby('Unnamed: 0').count()

# 필요없는 행 삭제 후 데이터 셋 저장

In [ ]:
# 행 삭제
스마트폰=스마트폰.drop(index=[0], axis=0)
스마트폰.head()
# 열 삭제 : 스마트폰=스마트폰.drop(columns=['co11','col2'], axis=1)
# 조건에 맞는 행 삭제 : 스마트폰=스마트폰[스마트폰['co11'] != 15]

   Unnamed: 0 스마트폰 관련 Unnamed: 2  ... Unnamed: 7 Unnamed: 8 Unnamed: 9
1         1.0    2015       2015  ...         60        500        100
2         2.0    2014       2015  ...         70         30         50
3         3.0    2015       2015  ...        120        300        200
4         4.0    2015       2016  ...         80         60        190
5         5.0    2015       2015  ...         90         30        500

[5 rows x 10 columns]

In [ ]:
스마트폰.shape

(24, 10)

In [ ]:
스마트폰.to_csv('스마트폰.csv')

# 데이터 셋 로드-csv

In [ ]:
import pandas as pd

In [ ]:
스마트폰=pd.read_csv('스마트폰.csv')

In [ ]:
스마트폰.shape

(23, 10)

In [ ]:
스마트폰.head()

   1  2015  2015.1    5  45  173  75   60  500  100
0  2  2014    2015  4.5  27  176  59   70   30   50
1  3  2015    2015  5.0  29  183  65  120  300  200
2  4  2015    2016  5.0  28  172  63   80   60  190
3  5  2015    2015  5.0  24  179  65   90   30  500
4  6  2016    2016  5.5  34  175  73   80  480  160

# 열 이름 변경

In [ ]:
# 행,열 하나 하나에 대해서 이름을 변경
스마트폰=스마트폰.rename(
    {
        '1':'순번',
        '2015':'출시년도'
    }, axis='columns'
)

In [ ]:
스마트폰.head()

   순번  출시년도  2015.1    5  45  173  75   60  500  100
0   2  2014    2015  4.5  27  176  59   70   30   50
1   3  2015    2015  5.0  29  183  65  120  300  200
2   4  2015    2016  5.0  28  172  63   80   60  190
3   5  2015    2015  5.0  24  179  65   90   30  500
4   6  2016    2016  5.5  34  175  73   80  480  160

In [ ]:
# 모든 열에 대해서 한꺼번에 변경
스마트폰.columns=['순번','출시년도',"구매시기", "디스플레이","연령","키","몸무게","스마트폰사용시간","컴퓨터사용시간","데이터사용량"]

In [ ]:
스마트폰.head()

   순번  출시년도  구매시기  디스플레이  연령    키  몸무게  스마트폰사용시간  컴퓨터사용시간  데이터사용량
0   2  2014  2015    4.5  27  176   59        70       30      50
1   3  2015  2015    5.0  29  183   65       120      300     200
2   4  2015  2016    5.0  28  172   63        80       60     190
3   5  2015  2015    5.0  24  179   65        90       30     500
4   6  2016  2016    5.5  34  175   73        80      480     160

In [ ]:
스마트폰.to_csv('스마트폰.csv')

# 데이터 셋을 다시 적재

In [ ]:
import pandas as pd
스마트폰=pd.read_csv('스마트폰.csv')

In [ ]:
스마트폰.head()

   Unnamed: 0  순번  출시년도  구매시기  디스플레이  연령    키  몸무게  스마트폰사용시간  컴퓨터사용시간  데이터사용량
0           0   2  2014  2015    4.5  27  176   59        70       30      50
1           1   3  2015  2015    5.0  29  183   65       120      300     200
2           2   4  2015  2016    5.0  28  172   63        80       60     190
3           3   5  2015  2015    5.0  24  179   65        90       30     500
4           4   6  2016  2016    5.5  34  175   73        80      480     160

In [ ]:
스마트폰=스마트폰.drop(columns=['Unnamed: 0'], axis=1)

In [ ]:
스마트폰.head()

   순번  출시년도  구매시기  디스플레이  연령    키  몸무게  스마트폰사용시간  컴퓨터사용시간  데이터사용량
0   2  2014  2015    4.5  27  176   59        70       30      50
1   3  2015  2015    5.0  29  183   65       120      300     200
2   4  2015  2016    5.0  28  172   63        80       60     190
3   5  2015  2015    5.0  24  179   65        90       30     500
4   6  2016  2016    5.5  34  175   73        80      480     160

#분석 데이터 식별

스마트폰$출시년도==2016

스마트폰[,9] > 500

In [ ]:
스마트폰출시년도조회=스마트폰.loc[
                    (
                        스마트폰['출시년도'] == 2016
                    )
]

In [ ]:
len(스마트폰출시년도조회)

8

In [ ]:
스마트폰출시년도조회.head()

    순번  출시년도  구매시기  디스플레이  연령    키  몸무게  스마트폰사용시간  컴퓨터사용시간  데이터사용량
4    6  2016  2016    5.5  34  175   73        80      480     160
5    7  2016  2016    6.0  40  169   77        60      300     170
12  14  2016  2016    6.0  41  181   88        60      120     130
15  17  2016  2016    5.5  35  184   72        90       90      70
16  18  2016  2016    6.0  34  176   71        90       60     130

In [ ]:
스마트폰데이터사용량=스마트폰.loc[
                    (
                        스마트폰['데이터사용량'] > 500
                    )
]

In [ ]:
len(스마트폰데이터사용량)

3

In [ ]:
스마트폰데이터사용량.head()

    순번  출시년도  구매시기  디스플레이  연령    키  몸무게  스마트폰사용시간  컴퓨터사용시간  데이터사용량
17  19  2015  2015    4.5  29  188   83       140      240     600
21  23  2015  2015    5.0  26  179   80       180       30    1100
22  24  2016  2016    6.0  25  177   76       120       90     700

# 분석 데이터 변환
일일 데이터 사용량을 5개의 군집으 로 나누어 평활한다.

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
# 클러스터 생성

kms=KMeans(n_clusters=5)

In [ ]:
스마트폰데이터사용량=스마트폰.loc[
                    (
                        스마트폰['데이터사용량'] != 0
                    )
]

In [ ]:
len(스마트폰데이터사용량)

23

In [ ]:
kms.fit(스마트폰데이터사용량)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
kms

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
kms.labels_

array([0, 2, 0, 4, 2, 2, 0, 4, 2, 3, 2, 0, 0, 0, 0, 0, 0, 3, 0, 4, 4, 1,
       3], dtype=int32)

In [ ]:
kms.predict(스마트폰데이터사용량)

array([0, 2, 0, 4, 2, 2, 0, 4, 2, 3, 2, 0, 0, 0, 0, 0, 0, 3, 0, 4, 4, 1,
       3], dtype=int32)

In [ ]:
center=kms.cluster_centers_
print(center)

[[  12.7        2015.2        2015.4           5.35         34.5
   176.6          73.3          67.           81.          104.        ]
 [  23.         2015.         2015.            5.           26.
   179.           80.          180.           30.         1100.        ]
 [   7.6        2015.4        2015.4           5.4          36.4
   175.           72.8          78.          384.          152.        ]
 [  18.         2015.         2015.            5.           28.66666667
   177.33333333   73.66666667  130.          210.          566.66666667]
 [  14.25       2015.         2015.            5.125        27.75
   178.25         69.           80.           75.          350.        ]]

In [ ]:
스마트폰_cbind=pd.concat([스마트폰, pd.DataFrame(kms.cluster_centers_)], axis=1)

In [ ]:
스마트폰_cbind.head()

   순번  출시년도  구매시기  디스플레이  연령  ...           5          6      7      8            9
0   2  2014  2015    4.5  27  ...  176.600000  73.300000   67.0   81.0   104.000000
1   3  2015  2015    5.0  29  ...  179.000000  80.000000  180.0   30.0  1100.000000
2   4  2015  2016    5.0  28  ...  175.000000  72.800000   78.0  384.0   152.000000
3   5  2015  2015    5.0  24  ...  177.333333  73.666667  130.0  210.0   566.666667
4   6  2016  2016    5.5  34  ...  178.250000  69.000000   80.0   75.0   350.000000

[5 rows x 20 columns]